# Generated by Django 5.0 on 2023-12-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aut", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="musordarab",
        ),
    ]
