#  main.py Copyright (C) 2024  Konta Boáz
#      This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
#      This is free software, and you are welcome to redistribute it
#      under certain conditions; type `show c' for details.
#   Last Modified: 2024. 04. 24. 18:17
import sys

print("Abi flags: ", sys.abiflags)
print("add audithook: ", sys.addaudithook)
print("argv: ", sys.argv)
print("sys base prefix dir: ", sys.base_prefix)
print("sys byteorder: ", sys.byteorder)
print("sys.maxsize: ", sys.maxsize)
print("sys builtin module names: ", sys.builtin_module_names)
# print("sys copyright: ", sys.copyright)
print("sys executable: ", sys.executable)
print("sys flags: ")
print("\t debug: ", sys.flags.debug)
print("\t inspect: ", sys.flags.inspect)
print("\t interactive: ", sys.flags.interactive)
print("\t isolated: ", sys.flags.isolated)
print("\t optimize: ", sys.flags.optimize)
print("\t dont write bytecode: ", sys.flags.dont_write_bytecode)
print("\t no user site: ", sys.flags.no_user_site)
print("\t ignore environment: ", sys.flags.ignore_environment)
print("\t verbose: ", sys.flags.verbose)
print("\t bytes warning: ", sys.flags.bytes_warning)
print("\t quiet: ", sys.flags.quiet)
print("\t hash randomization: ", sys.flags.hash_randomization)
print("\t dev mode: ", sys.flags.dev_mode)
print("\t utf8 mode: ", sys.flags.utf8_mode)
print("\t safe path: ", sys.flags.safe_path)
print("\t int max str digits: ", sys.flags.int_max_str_digits)
print("sys float info: ")
print("\t epsilon: ", sys.float_info.epsilon)
print("\t dig: ", sys.float_info.dig)
print("\t mant dig: ", sys.float_info.mant_dig)
print("\t max: ", sys.float_info.max)
print("\t max exp: ", sys.float_info.max_exp)
print("\t max 10 exp: ", sys.float_info.max_10_exp)
print("\t min: ", sys.float_info.min)
print("\t min exp: ", sys.float_info.min_exp)
print("\t min 10 exp: ", sys.float_info.min_10_exp)
print("\t radix: ", sys.float_info.radix)
print("\t rounds: ", sys.float_info.rounds)
